# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: textprocessor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'textprocessor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13textprocessor.proto\x12\rtextprocessor\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\'\n\x11WordCountResponse\x12\x12\n\nword_count\x18\x01 \x01(\x05\"\'\n\x11\x43harCountResponse\x12\x12\n\nchar_count\x18\x01 \x01(\x05\"+\n\tWordChunk\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x01(\x05\"R\n\x12TotalCountResponse\x12\x13\n\x0btotal_words\x18\x01 \x01(\x05\x12\x13\n\x0btotal_chars\x18\x02 \x01(\x05\x12\x12\n\ntext_count\x18\x03 \x01(\x05\"P\n\x10\x41nalysisResponse\x12\x15\n\rcurrent_words\x18\x01 \x01(\x05\x12\x15\n\rcurrent_chars\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t2\xa0\x03\n\rTextProcessor\x12J\n\nCountWords\x12\x1a.textprocessor.TextRequest\x1a .textprocessor.WordCountResponse\x12O\n\x0f\x43ountCharacters\x12\x1a.textprocessor.TextRequest\x1a .textprocessor.CharCountResponse\x12\x45\n\x0bStreamWords\x12\x1a.textprocessor.TextRequest\x1a\x18.textprocessor.WordChunk0\x01\x12U\n\x12\x43ountMultipleTexts\x12\x1a.textprocessor.TextRequest\x1a!.textprocessor.TotalCountResponse(\x01\x12T\n\x11\x41nalyzeTextStream\x12\x1a.textprocessor.TextRequest\x1a\x1f.textprocessor.AnalysisResponse(\x01\x30\x01\x42 Z\x1eserver-b-chars/textprocessorpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'textprocessor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036server-b-chars/textprocessorpb'
  _globals['_TEXTREQUEST']._serialized_start=38
  _globals['_TEXTREQUEST']._serialized_end=65
  _globals['_WORDCOUNTRESPONSE']._serialized_start=67
  _globals['_WORDCOUNTRESPONSE']._serialized_end=106
  _globals['_CHARCOUNTRESPONSE']._serialized_start=108
  _globals['_CHARCOUNTRESPONSE']._serialized_end=147
  _globals['_WORDCHUNK']._serialized_start=149
  _globals['_WORDCHUNK']._serialized_end=192
  _globals['_TOTALCOUNTRESPONSE']._serialized_start=194
  _globals['_TOTALCOUNTRESPONSE']._serialized_end=276
  _globals['_ANALYSISRESPONSE']._serialized_start=278
  _globals['_ANALYSISRESPONSE']._serialized_end=358
  _globals['_TEXTPROCESSOR']._serialized_start=361
  _globals['_TEXTPROCESSOR']._serialized_end=777
# @@protoc_insertion_point(module_scope)
